### ISSUE TITLE
Update for GNOME 43

### ISSUE THREAD

**Issue by scarf** [mgalgs/gnome-shell-system-monitor-applet#25]
If I add "43" to the metadata and try to load it I get this error:
`StatusArea.aggregateMenu is undefined`

**Comment by mgalgs** [comment]
Hi, this sounds like a bug that should be reported upstream: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet

This repo is for packaging purposes only.

**Comment by scarf** [comment]
I don't understand, what's the point of your fork?  I thought upstream was abandoned.  Indeed there hasn't been a release since April 2019 and no code updates since April of this year.  Still, I do see a recent [issue there re Gnome 43](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/749).  There is a [workaround](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/749#issuecomment-1250049538) mentioned too.  but again am still unclear why no updates are made here while others are reporting issues on a dead repo?

**Comment by mgalgs** [comment]
Fair enough, I honestly hadn't checked upstream recently, but it looks pretty abandoned indeed... I haven't done any actual development on this package but am happy to integrate patches. Let me do a bit more due diligence and ponder opening this repo to new development.

Regarding [the workaround](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/749#issuecomment-1255429167) mentioned above, I wouldn't integrate that patch since it kills battery status support, but if someone submits a proper fix I'll happily take a look.

**Comment by mgalgs** [comment]
I took a look at [the open PRs](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pulls) on upstream, and I don't see anything too compelling there that I would feel strongly about pulling in to this repo... So I'm leaning towards leaving this repo in its current mode of operation (build+package only, no new development).

If a proper fix for Gnome 43 is submitted to upstream and they're still not responsive I'd be happy to reconsider that decision, but for now it looks like upstream is doing all right integrating important patches.

Open to further discussion if anyone disagrees with my conclusion that the open PRs in upstream aren't important enough to bring in here and start diverging from upstream.
