### ISSUE TITLE
ERROR meta is null

### ISSUE THREAD

**Issue by danlists** [mgalgs/gnome-shell-system-monitor-applet#83]
The extension won't load.  Looking Glass shows the error to be "meta is null".
I tried logging out and back in.
Ubuntu 22.04.4 LTS
GNOME Shell 42.9

**Comment by mgalgs** [comment]
Please check out #36. You're probably missing some dependencies.

**Comment by mgalgs** [comment]
Yeah the pop-up broke somewhere along the way, not exactly sure when... In GS >=45 we have to come up with a new way of checking for dependencies since the old way doesn't work in es6 (this effort is tracked in #69), and there's probably not enough interest in GS < 45 to get the old method of checking fixed.

**Comment by mgalgs** [comment]
> there's probably not enough interest in GS < 45 to get the old method of checking fixed.

Having said that, PRs against the `pre-45` branch are more than welcome!
